config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, only: [:sign_in, :sign_out, :session], controllers: {
      sessions: "admins/sessions",
      registrations: "admins/registrations"
    }

  devise_scope :admin do
    get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    put 'admins' => 'admins/registrations#update'
  end

  namespace :admin do
    resources :achievements
    resources :admins, :except => [:edit, :update]
    resources :bounds do
      resources :beacons
    end
    resources :exhibitions
    resources :groups
    resources :notifications
    resources :treasures
    resources :users, :except => [:new, :edit, :create, :update]
    get '/' => 'home#dashboard'
  end

  namespace :api, defaults: { format: :json } do
    resources :achievements, only: [:index]
    resources :beacons, only: [:index]
    resources :bounds, only: [:index] do
      member do
        post 'check_in'
      end
    end
    resources :exhibitions, only: [:index, :show] do
      member do
        post 'vote'
      end
    end
    resources :notifications, only: [:index]
    resources :statuses, only: [:index, :create, :destroy] do
      member do
        post 'favorites' => 'statuses#fav'
        delete 'favorites' => 'statuses#unfav'
      end
    end
    resources :treasures, only: [:index, :show] do
      member do
        post 'take'
      end
    end
    resources :users, only: [:show, :create]
  end

end

app/models/notification.rb
# == Schema Information
#
# Table name: notifications
#
#  id         :integer          not null, primary key
#  content    :text
#  created_at :datetime
#  updated_at :datetime
#

class Notification < ActiveRecord::Base
  # TODO: 投稿者（admin）アカウントとの紐付けは不要？
  # TODO: 本文の長さに関するvalidationの検討
  validates :content, presence: true
end

app/controllers/admin/notifications_controller.rb
class Admin::NotificationsController < Admin::BaseController
  before_action :set_admin_notification, only: [:show, :edit, :update, :destroy]

  def index
    @notifications = Notification.all
  end

  def show
  end

  def new
    @notification = Notification.new
  end

  def edit
  end

  def create
    @notification = Notification.new(admin_notification_params)

    respond_to do |format|
      if @notification.save
        format.html { redirect_to admin_notifications_url, notice: 'Notification was successfully created.' }
        format.json { render :show, status: :created, location: @notification }
      else
        format.html { render :new }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @notification.update(admin_notification_params)
        format.html { redirect_to admin_notification_url, notice: 'Notification was successfully updated.' }
        format.json { render :show, status: :ok, location: @notification }
      else
        format.html { render :edit }
        format.json { render json: @notification.errors, status: :unprocessable_entity }
      end
    end
  end

def destroy
    @notification.destroy
    respond_to do |format|
      format.html { redirect_to admin_notifications_url, notice: 'Notification was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_notification
      @notification = Notification.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_notification_params
      params.require(:notification).permit(:content)
    end
end

app/controllers/api/notifications_controller.rb
class Api::NotificationsController < Api::BaseController

  def index
     @notifications = Notification.all
     render json: @notifications
  end
end

app/helpers/admin/notifications_helper.rb
module Admin::NotificationsHelper
end

app/helpers/api/notifications_helper.rb
module Api::NotificationsHelper
end

app/views/admin/notifications/_form.html.erb
<%= form_for([:admin, @notification], html: {class: "form-horizontal"}) do |f| %>
  <% if @notification.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notification.errors.count, "error") %> prohibited this admin_notification from being saved:</h2>

      <ul>
      <% @notification.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="form-notification">
      <%= f.label :content, class: "col-sm-3 control-label" %>
      <div class="col-sm-9">
        <%= f.text_area :content, autofocus: true, placeholder: "Content", :class => "form-control" %>
        <br>
      </div>
    </div>
    <div class="form-notification">
      <%= admin_submit_btn %>
    </div>
  <br>
<% end %>

app/views/admin/notifications/edit.html.erb
<h1 class="first">Editing notification</h1>

<%= render 'form' %>

<%= admin_show_btn admin_notification_path(@notification) %>
<%= admin_back_btn admin_notifications_path %>

app/views/admin/notifications/index.html.erb
<h1 class="first">お知らせ一覧 <small>- Notifications</small></h1>
<br>

<table class="table table-hover table-row-clickable">

  <tbody>
    <% @notifications.each do |notification| %>
      <tr class="pointer-cursor" data-href="<%= admin_notification_path(notification) %>">
        <td><%= notification.content[0...16] %>...</td>
        <td>
          <%= admin_edit_btn edit_admin_notification_path(notification) %>
          <%= admin_destroy_btn admin_notification_path(notification) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notification', new_admin_notification_path %>

app/views/admin/notifications/new.html.erb
<h1 class="first">New notification</h1>

<%= render 'form' %>

<%= admin_back_btn admin_notifications_path %>

app/views/admin/notifications/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <span class="pink">Content:</span>
  <%= @notification.content %>
</p>

<%= admin_edit_btn edit_admin_notification_path(@notification) %>
<%= admin_back_btn admin_notifications_path %>