config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, only: [:sign_in, :sign_out, :session], controllers: {
      sessions: "admins/sessions",
      registrations: "admins/registrations"
    }

  devise_scope :admin do
    get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    put 'admins' => 'admins/registrations#update'
  end

  namespace :admin do
    resources :achievements
    resources :admins, :except => [:edit, :update]
    resources :bounds do
      resources :beacons
    end
    resources :exhibitions
    resources :groups
    resources :notifications
    resources :treasures
    resources :users, :except => [:new, :edit, :create, :update]
    get '/' => 'home#dashboard'
  end

  namespace :api, defaults: { format: :json } do
    resources :achievements, only: [:index]
    resources :beacons, only: [:index]
    resources :bounds, only: [:index] do
      member do
        post 'check_in'
      end
    end
    resources :exhibitions, only: [:index, :show] do
      member do
        post 'vote'
      end
    end
    resources :notifications, only: [:index]
    resources :statuses, only: [:index, :create, :destroy] do
      member do
        post 'favorites' => 'statuses#fav'
        delete 'favorites' => 'statuses#unfav'
      end
    end
    resources :treasures, only: [:index, :show] do
      member do
        post 'take'
      end
    end
    resources :users, only: [:show, :create]
  end

end

app/models/achievement.rb
# == Schema Information
#
# Table name: achievements
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  condition   :string(255)
#  description :string(255)
#  icon_url    :string(255)
#  created_at  :datetime
#  updated_at  :datetime
#

class Achievement < ActiveRecord::Base
  validates :name, presence: true
  validates :condition, presence: true
  validates :description, presence: true

  mount_uploader :icon_url, AchievementUploader
end

app/controllers/admin/achievements_controller.rb
class Admin::AchievementsController < Admin::BaseController
  before_action :set_admin_achievement, only: [:show, :edit, :update, :destroy] 

  # GET /admin/achievements
  # GET /admin/achievements.json
  def index
    @achievements = Achievement.all
  end

  # GET /admin/achievements/1
  # GET /admin/achievements/1.json
  def show
  end

  # GET /admin/achievements/new
  def new
    @achievement = Achievement.new
  end

  # GET /admin/achievements/1/edit
  def edit
  end

  # POST /admin/achievements
  # POST /admin/achievements.json
  def create
    @achievement = Achievement.new(admin_achievement_params)

    respond_to do |format|
      if @achievement.save
        format.html { redirect_to admin_achievements_url, notice: 'Achievement was successfully created.' }
        format.json { render :show, status: :created, location: @achievement }
      else
        format.html { render :new }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/achievements/1
  # PATCH/PUT /admin/achievements/1.json
  def update
    respond_to do |format|
      if @achievement.update(admin_achievement_params)
        format.html { redirect_to admin_achievements_url, notice: 'Achievement was successfully updated.' }
        format.json { render :show, status: :ok, location: @achievement }
      else
        format.html { render :edit }
        format.json { render json: @achievement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/achievements/1
  # DELETE /admin/achievements/1.json
  def destroy
    @achievement.destroy
    respond_to do |format|
      format.html { redirect_to admin_achievements_url, notice: 'Achievement was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_achievement
      @achievement = Achievement.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_achievement_params
      params.require(:achievement).permit(:name, :condition, :description, :icon_url)
    end
end

app/controllers/api/achievements_controller.rb
class Api::AchievementsController < Api::BaseController

  def index
    @achievements = Achievement.all
    render json: @achievements
  end
end

app/helpers/admin/achievements_helper.rb
module Admin::AchievementsHelper
end

app/helpers/api/achievements_helper.rb
module Api::AchievementsHelper
end

app/views/admin/achievements/_form.html.erb
<%= form_for([:admin, @achievement]) do |f| %>
<% if @achievement.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@achievement.errors.count, "error") %> prohibited this admin_achievement from being saved:</h2>
    <ul>
      <% @achievement.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control" %>
    <br>
  </div>
</div>

<div class="form-group">
  <%= f.label :condition, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :condition, placeholder: "Condition", class: "form-control" %>
    <br>
  </div>
</div>

<div class="form-group">
  <%= f.label :description, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :description, placeholder: "Description", class: "form-control" %>
    <br>
  </div>
</div>

<div class="form-group">
   <%= f.label :icon_url, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.file_field :icon_url %>
    <br>
  </div>
</div>

<br>
<div class="actions">
  <%= admin_submit_btn %>
</div>
<br>
<% end %>

app/views/admin/achievements/edit.html.erb
<h1 class="first">Editing achievement</h1>

<%= render 'form' %>

<%= admin_show_btn admin_achievement_path(@achievement) %>
<%= admin_back_btn admin_achievements_path %>

app/views/admin/achievements/index.html.erb
<h1 class="first">実績一覧 <small>- Achievements</small></h1>
<br>

<table class="table table-hover table-row-clickable">

  <tbody>
    <% @achievements.each do |achievement| %>
      <tr class="pointer-cursor" data-href="<%= admin_achievement_path(achievement) %>">
        <td><%= achievement.name %></td>
        <td>
          <%= admin_edit_btn edit_admin_achievement_path(achievement) %>
          <%= admin_destroy_btn admin_achievement_path(achievement) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Achievement', new_admin_achievement_path %>

app/views/admin/achievements/new.html.erb
<h1 class="first">New achievement</h1>

<%= render 'form' %>

<%= admin_back_btn admin_achievements_path %>

app/views/admin/achievements/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <span class="pink">Name:</span>
  <%= @achievement.name %>
</p>

<p class="lead">
  <span class="pink">Condition:</span>
  <%= @achievement.condition %>
</p>

<p class="lead">
  <span class="pink">Description:</span>
  <%= @achievement.description %>
</p>

<p class="lead">
  <span class="pink">Icon:</span>
    <%= image_tag(@achievement.icon_url) if @achievement.icon_url.present? %>
</p>

<%= admin_edit_btn edit_admin_achievement_path(@achievement) %>
<%= admin_back_btn admin_achievements_path %>