config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, only: [:sign_in, :sign_out, :session], controllers: {
      sessions: "admins/sessions",
      registrations: "admins/registrations"
    }

  devise_scope :admin do
    get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    put 'admins' => 'admins/registrations#update'
  end

  namespace :admin do
    resources :achievements
    resources :admins, :except => [:edit, :update]
    resources :bounds do
      resources :beacons
    end
    resources :exhibitions
    resources :groups
    resources :notifications
    resources :treasures
    resources :users, :except => [:new, :edit, :create, :update]
    get '/' => 'home#dashboard'
  end

  namespace :api, defaults: { format: :json } do
    resources :achievements, only: [:index]
    resources :beacons, only: [:index]
    resources :bounds, only: [:index] do
      member do
        post 'check_in'
      end
    end
    resources :exhibitions, only: [:index, :show] do
      member do
        post 'vote'
      end
    end
    resources :notifications, only: [:index]
    resources :statuses, only: [:index, :create, :destroy] do
      member do
        post 'favorites' => 'statuses#fav'
        delete 'favorites' => 'statuses#unfav'
      end
    end
    resources :treasures, only: [:index, :show] do
      member do
        post 'take'
      end
    end
    resources :users, only: [:show, :create]
  end

end

app/models/treasure.rb
# == Schema Information
#
# Table name: treasures
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  description :string(255)
#  image_url   :string(255)
#  bound_id    :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class Treasure < ActiveRecord::Base
  
  belongs_to :bound

  has_many :taken_treasures
  has_many :users, through: :taken_treasures

  # TODO: 文字数制限等に関するvalidationの検討
  validates_presence_of :name, :description

  mount_uploader :image_url, TreasureUploader
end

app/controllers/admin/treasures_controller.rb
class Admin::TreasuresController < Admin::BaseController
  before_action :set_admin_treasure, only: [:show, :edit, :update, :destroy]

  def index
    @treasures = Treasure.all
  end

  def show
  end

  def new
    @treasure = Treasure.new
  end

  def edit
  end

  def create
    @treasure = Treasure.new(admin_treasure_params)

    respond_to do |format|
      if @treasure.save
        format.html { redirect_to admin_treasures_url, notice: 'Treasures was successfully created.' }
        format.json { render :show, status: :created, location: @treasure }
      else
        format.html { render :new }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @treasure.update(admin_treasure_params)
        format.html { redirect_to admin_treasures_url, notice: 'Treasures was successfully updated.' }
        format.json { render :show, status: :ok, location: @treasure }
      else
        format.html { render :edit }
        format.json { render json: @treasure.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @treasure.destroy
    respond_to do |format|
      format.html { redirect_to admin_treasures_url, notice: 'Treasure was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_admin_treasure
      @treasure = Treasure.find(params[:id])
    end

    def admin_treasure_params
      params.require(:treasure).permit(:name, :description, :image_url)
    end
end

app/controllers/api/treasures_controller.rb
class Api::TreasuresController < Api::BaseController
  before_action :set_treasure, only: [:take, :show]

  def index
    @treasures = Treasure.all
    render json: @treasures
  end

  def show
    render json: @treasure
  end

  def take
    if current_user.take(@treasure)
      render json: @treasure, status: :created
    else
      render json: { error: { message: 'That treasure has already taken by current user.' } }, status: :conflict
    end
  end

  private
    def set_treasure
      @treasure = Treasure.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render json: { error: { message: 'That treasure does not exist.'} }, status: :not_found
    end
end

app/helpers/admin/treasures_helper.rb
module Admin::TreasuresHelper
end

app/helpers/api/treasures_helper.rb
module Api::TreasuresHelper
end

app/views/admin/treasures/_form.html.erb
<%= form_for([:admin, @treasure], html: {class: "form-horizontal"}) do |f| %>
<% if @treasure.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@treasure.errors.count, "error") %> prohibited this admin_treasure from being saved:</h2>

  <ul>
    <% @treasure.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :name, autofocus: true, placeholder: "Name", :class => "form-control" %>
    <br>
  </div>
</div>

<div class="form-group">
  <%= f.label :description, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :description, placeholder: "Description", :class => "form-control" %>
    <br>
  </div>
</div>

<div class="form-group">
  <%= f.label :image_url, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
      <%= f.file_field :image_url %>
    <br>
  </div>
</div>
<div class="actions">
  <%= admin_submit_btn %>
</div>
<br>
<% end %>

app/views/admin/treasures/edit.html.erb
<h1 class="first">Editing treasure</h1>

<%= render 'form' %>

<%= admin_show_btn admin_treasure_path(@treasure) %>
<%= admin_back_btn admin_treasures_path %>

app/views/admin/treasures/index.html.erb
<h1 class="first">宝物一覧 <small>- Treasures</small></h1>
<br>

<table class="table table-hover table-row-clickable">

  <tbody>
    <% @treasures.each do |treasure| %>
      <tr class="pointer-cursor" data-href="<%= admin_treasure_path(treasure) %>">
        <td><%= treasure.name %></td>
        <td>
          <%= admin_edit_btn edit_admin_treasure_path(treasure) %>
          <%= admin_destroy_btn admin_treasure_path(treasure) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Treasure', new_admin_treasure_path %>

app/views/admin/treasures/new.html.erb
<h1 class="first">New treasure</h1>

<%= render 'form' %>

<%= admin_back_btn admin_treasures_path %>

app/views/admin/treasures/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <span class="pink">Name:</span>
  <%= @treasure.name %>
</p>

<p class="lead">
  <span class="pink">Description:</span>
  <%= @treasure.description %>
</p>

<p class="lead">
  <span class="pink">Image_url:</span>
  <%= image_tag(@treasure.image_url) if @treasure.image_url.present? %>
</p>

<%= admin_edit_btn edit_admin_treasure_path(@treasure) %>
<%= admin_back_btn admin_treasures_path %>