config/routes.rb
Rails.application.routes.draw do

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  devise_for :admins, only: [:sign_in, :sign_out, :session], controllers: {
      sessions: "admins/sessions",
      registrations: "admins/registrations"
    }

  devise_scope :admin do
    get 'admins/edit' => 'admins/registrations#edit', as: 'edit_admin_registration'
    patch 'admins' => 'admins/registrations#update', as: 'admin_registration'
    put 'admins' => 'admins/registrations#update'
  end

  namespace :admin do
    resources :achievements
    resources :admins, :except => [:edit, :update]
    resources :bounds do
      resources :beacons
    end
    resources :exhibitions
    resources :groups
    resources :notifications
    resources :treasures
    resources :users, :except => [:new, :edit, :create, :update]
    get '/' => 'home#dashboard'
  end

  namespace :api, defaults: { format: :json } do
    resources :achievements, only: [:index]
    resources :beacons, only: [:index]
    resources :bounds, only: [:index] do
      member do
        post 'check_in'
      end
    end
    resources :exhibitions, only: [:index, :show] do
      member do
        post 'vote'
      end
    end
    resources :notifications, only: [:index]
    resources :statuses, only: [:index, :create, :destroy] do
      member do
        post 'favorites' => 'statuses#fav'
        delete 'favorites' => 'statuses#unfav'
      end
    end
    resources :treasures, only: [:index, :show] do
      member do
        post 'take'
      end
    end
    resources :users, only: [:show, :create]
  end

end

app/models/bound.rb
# == Schema Information
#
# Table name: bounds
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Bound < ActiveRecord::Base

  has_many :beacons
  has_many :check_ins
  has_many :exhibitions
  has_many :treasures

  validates_presence_of :name
end

app/controllers/admin/bounds_controller.rb
class Admin::BoundsController < Admin::BaseController
  before_action :set_admin_bound, only: [:show, :edit, :update, :destroy]

  def index
    @bounds = Bound.all
  end

  def show
    @beacons = @bound.beacons
  end

  def new
    @bound = Bound.new
  end

  def edit
  end

  def create
    @bound = Bound.new(admin_bound_params)

    respond_to do |format|
      if @bound.save
        format.html { redirect_to admin_bounds_url, notice: 'Bound was successfully created.' }
        format.json { render :show, status: :ok, location: @bound }
      else
        format.html { render :edit }
        format.json { render json: @bound.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @bound.update(admin_bound_params)
        format.html { redirect_to admin_bounds_url, notice: 'Bound was successfully updated.' }
        format.json { render :show, status: :ok, location: @bound }
      else
        format.html { render :edit }
        format.json { render json: @bound.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @bound.destroy
    respond_to do |format|
      format.html { redirect_to admin_bounds_url, notice: 'Bound was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_bound
      @bound = Bound.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def admin_bound_params
      params.require(:bound).permit(:name)
    end
end

app/controllers/api/bounds_controller.rb
class Api::BoundsController < Api::BaseController
  before_action :set_bound, only: [:check_in]

  def index
    @bounds = Bound.all
    render json: @bounds
  end

  def check_in
    @check_in = current_user.check_in(@bound)
    render json: @bound, status: :created
  end
  
  private
    def set_bound
      @bound = Bound.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      render json: {error: { message: 'That bound does not exist.' }}, status: :not_found
    end
end

app/helpers/admin/bounds_helper.rb
module Admin::BoundsHelper
end

app/helpers/api/bounds_helper.rb
module Api::BoundsHelper
end

app/views/admin/bounds/_form.html.erb
<%= form_for([:admin, @bound], html: {class: "form-horizontal"}) do |f| %>
<% if @bound.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(@bound.errors.count, "error") %> prohibited this admin_bound from being saved:</h2>

  <ul>
    <% @bound.errors.full_messages.each do |message| %>
    <li><%= message %></li>
    <% end %>
  </ul>
</div>
<% end %>

<div class="form-group">
  <%= f.label :name, class: "col-sm-3 control-label" %>
  <div class="col-sm-9">
    <%= f.text_field :name, autofocus: true, placeholder: "Name", class: "form-control" %>
    <br>
  </div>
</div>
<br>
<div class="actions">
  <%= admin_submit_btn %>
</div>
<br>
<% end %>

app/views/admin/bounds/edit.html.erb
<h1 class="first">Editing bound</h1>

<%= render 'form' %>

<%= admin_show_btn admin_bound_path(@bound) %>
<%= admin_back_btn admin_bounds_path %>

app/views/admin/bounds/index.html.erb
<h1 class="first">エリア一覧 <small>- Bounds</small></h1>
<br>

<table class="table table-hover table-row-clickable">

  <tbody>
    <% @bounds.each do |bound| %>
      <tr class="pointer-cursor" data-href="<%= admin_bound_path(bound) %>">
        <td><%= bound.name %></td>
        <td><%= pluralize(bound.beacons.count, "Beacon") %></td>
        <td>
          <%= admin_edit_btn edit_admin_bound_path(bound) %>
          <%= admin_new_btn new_admin_bound_beacon_path(bound) %>
          <%= admin_destroy_btn admin_bound_path(bound) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Bound', new_admin_bound_path %>

app/views/admin/bounds/new.html.erb
<h1 class="first">New bound</h1>

<%= render 'form' %>

<%= admin_back_btn admin_bounds_path %>

app/views/admin/bounds/show.html.erb
<p id="notice"><%= notice %></p>

<p class="lead">
  <span class="pink">Bound Name:</span>
  <%= @bound.name %>
  <%= render @beacons %>
</p>

<%= admin_edit_btn edit_admin_bound_path(@bound) %>
<%= admin_back_btn admin_bounds_path %>